### ISSUE TITLE
Race conditions with aggregators exposing the same nodes

### ISSUE THREAD

**Issue by andreasevers** [ordina-jworks/microservices-dashboard-server#24] opened 2016-07-07 13:20 UTC
In case one aggregator is faster than another, it can expose a node which is not yet returned from the other aggregator. Merging doesn't seem to work well.

**Comment by TYsewyn** [comment] 2016-07-11 08:04
I'm not able to replicate this issue. Merging based on the ID should work just fine.
Maybe the issue is with RxJava?

**Comment by TYsewyn** [comment] 2019-02-24 20:46
Closing this issue in favor of version 2.x which does not have a notion of nodes.
Version 1.x hasn't been maintained for over a year now and is now EOL.

**Closed as completed by TYsewyn** 2019-02-24 20:46 UTC
Labels: type: bug
